FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
RUN pwd
RUN ./mvnw package
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/quarkus-app/quarkus-run.jar /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
